# Generated by Django 3.0.5 on 2020-05-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('TeamSize', models.IntegerField(default=1)),
                ('Event_Pics', models.ImageField(upload_to='event_pics')),
            ],
        ),
        migrations.CreateModel(
            name='urd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('collegename', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('mobilenum', models.CharField(max_length=100)),
                ('events', models.CharField(max_length=100)),
            ],
        ),
    ]
